# Generated by Django 4.1.7 on 2023-05-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='articles',
            name='aughtor',
            field=models.CharField(max_length=20, null=True, verbose_name='Автор'),
        ),
    ]
